### ISSUE TITLE
Need to create Install Behavior

### ISSUE THREAD

**Issue by ssnak3** [asjimene/SCCM-Application-Packager#11]
Hi,

First of all good job on the script, it is of great help!

The issue that I am facing is suddenly when running the script first time (wanted to re-install the whole script components) is that in the logs says "WARN: The Requirements Application has been created, please do the following:
"WARN: The Requirements Application has been created, please do the following:"
"1. Add an "Install Behavior" entry to the "Templates" deployment type of the Application Requirements Template Application"
"2. Run the SCCMPackager again to finish prerequisite setup and begin packaging software."

I tried adding some dummy Install Behavior to Application Requirements Template Application - Requirements Template but it still is showing the same error.
Can you please advise what could I be doing wrong?

Thank you!

**Comment by asjimene** [comment]
I would double check and make sure the Application name in the SCCMPackager.prefs is set correctly, by default it should be set to "Application Requirements Template 1". If that name doesn't match your template application in SCCM exactly it is not going to continue.

**Comment by ssnak3** [comment]
Hi,

Yes, the name is "Application Requirements Template" and version is set to "1".

Here is the log that shows up:
6/27/2019 11:41:25 AM - --- Starting SCCM AutoPackager ---
6/27/2019 11:41:25 AM - Creating SCCMPackager Folder
6/27/2019 11:41:25 AM - Allowing All Cookies to Download (This prevents the script from freezing on a download)
6/27/2019 11:41:25 AM - All Recipes: _Application Requirements Template.xml
6/27/2019 11:41:25 AM - Importing Content for _Application Requirements Template.xml
6/27/2019 11:41:25 AM - Starting Global Requirements Script: "C:\Test\SCCMPackager\ExtraFiles\Scripts\CreateGlobalConditionsAndRequirements.ps1"
6/27/2019 11:41:25 AM - Creating Global Conditions - If Needed
6/27/2019 11:41:30 AM - WARN: The Requirements Application is being created, please run the SCCMPackager again to finish prerequisite setup and begin packaging software.
6/27/2019 11:41:30 AM - Downloading Application Requirements Template from https://raw.githubusercontent.com/asjimene/SCCM-Application-Packager/master/README.md
6/27/2019 11:41:30 AM - Completed Downloading Application Requirements Template
6/27/2019 11:41:30 AM - Found Version 1 from Download FullVersion: 
6/27/2019 11:41:31 AM - 1 is not a new Version - Moving to next application
6/27/2019 11:41:31 AM - Continue to Download: False
6/27/2019 11:41:31 AM - WARN: The Requirements Application has been created, please do the following:
1. Add an "Install Behavior" entry to the "Templates" deployment type of the Application Requirements Template Application
2. Run the SCCMPackager again to finish prerequisite setup and begin packaging software.
Exiting.

**Comment by asjimene** [comment]
Very interesting... Let's do this, just to get you past this point. I'll have to look at the script later and see if this is a bug for everyone.

in the "SCCM-Application-Packager\ExtraFiles\Scripts\CreateGlobalConditionsAndRequirements.ps1" file, edit line 37 from:
if (Get-CMApplication -Name $Global:RequirementsTemplateAppName -Fast) {
to
if ($true) {

I would remove all your other recipes from the recipes folder before doing this, and after the script finishes, check the template app to make sure it was created correctly with all of the requirements etc generated.

**Comment by asjimene** [comment]
Hmm... I'm also wondering if the ConfigurationManager Module isn't being loaded... Are there any errors in the powershell window while the script is running?

**Comment by ssnak3** [comment]
Hi,

Sorry for the late reply, was busy lately and was not able to troubleshoot.

Configmgr module was loaded and no errors were poping out except those warnings above in the log.

When switched to "$true" like you suggested and now the script is able to finish creating Application Template, but it did not add conditions to it.

One question, if I add some custom "Global Conditions" to the Application Template manually, will the script be able to pull that one and place it in future applications packaged by script.
Because I have my own Conditions and the ones script creates are note neccessary so it is creating additional conditions with no reason and is it possible to skip whole "CreateGlobalConditionsAndRequirements.ps1" ?

Thanks.

**Comment by asjimene** [comment]
Totally understand! I have been crazy busy myself.

Yes, the script will be able to pull any conditions/requirements that are assigned to the template app. Feel free to create your own and use those in your recipes. You can skip the "CreateGlobalConditionsandRequirements.ps1" by commenting it out in "Recipes/_Application Requirements Template.xml". The line you'll want to comment out is:
`Invoke-Expression "&amp; `"$ScriptRoot\ExtraFiles\Scripts\CreateGlobalConditionsAndRequirements.ps1`"";`

change it to 
`#Invoke-Expression "&amp; `"$ScriptRoot\ExtraFiles\Scripts\CreateGlobalConditionsAndRequirements.ps1`"";`

And that should be it

Hope this works! Thanks!

**Comment by asjimene** [comment]
Hopefully you got things working, at least with the workaround. I have been unable to replicate, so I am going to go ahead and close this issue.
