### ISSUE TITLE
Interested in working with AutoPkg for Windows?

### ISSUE THREAD

**Issue by NickETH** [asjimene/SCCM-Application-Packager#12]
Hi Andrew,
just saw your project. That is a really cool thing.
I am working in the same field, but we use 
[AutoPkg for Windows](https://github.com/NickETH/autopkg/tree/win).
A few guys have ported the original AutoPkg to Windows, which was not that hard, because it is written in Python. The intention is to port this fork back to the main project ASAP.
What i like the most so far with AutoPkg, that there is already a huge developer and user base on the Mac-side, from which we can profit.
So, i concentrated mostly on building processors for specific task around the Windows Installer field.

Are you maybe interested to merge your project with AutoPkg for Windows?
That would give you more time to focus on the (huge) field around importing and configuring stuff on SCCM.
What do you think about this?

BR, Nick

**Comment by asjimene** [comment]
Hello,

I appreciate the invitation. I will definitely be checking out Autopkg for Windows, but I will not be merging with that project at this time. Thank you!
