### ISSUE TITLE
Add Ability to Deploy to Multiple Collections

### ISSUE THREAD

**Issue by Clayo84** [asjimene/SCCM-Application-Packager#18]
Adding the following code at line 1054 in the SCCMPackager.ps1 would allow for deploying the application to multiple collections by specifying additional DeploymentCollection nodes.

`ForEach($Collection in $Recipe.ApplicationDef.Deployment.DeploymentCollection){`

Also, you'll need to replace $Recipe.ApplicationDef.Deployment.DeploymentCollection with $Collection in the New-CMApplicationDeployment parameters.

And the corresponding } at line 1065.

**Comment by asjimene** [comment]
Thank you for the feedback! This behavior has been added in commit: https://github.com/asjimene/SCCM-Application-Packager/commit/fbaa971955b20822a6333c37bec1371b6beb7ee9
