### ISSUE TITLE
Quotes missing on line 372

### ISSUE THREAD

**Issue by luzkenin** [asjimene/SCCM-Application-Packager#2]
When deploying an application if the ApplicationDescription has spaces the app creation will fail. 

`New-CMApplication -Name "$ApplicationName $ApplicationSWVersion" -Description $ApplicationDescription -Publisher "$ApplicationPublisher" -SoftwareVersion $ApplicationSWVersion -OptionalReference $ApplicationDocURL -AutoInstall $ApplicationAutoInstall -ReleaseDate (Get-Date) -LocalizedName "$ApplicationName $ApplicationSWVersion" -LocalizedDescription $ApplicationDescription -UserDocumentation "$ApplicationDocURL" -IconLocationFile $ApplicationIcon`

Fix is to add quotations around $ApplicationDescription:
`New-CMApplication -Name "$ApplicationName $ApplicationSWVersion" -Description $ApplicationDescription -Publisher "$ApplicationPublisher" -SoftwareVersion $ApplicationSWVersion -OptionalReference $ApplicationDocURL -AutoInstall $ApplicationAutoInstall -ReleaseDate (Get-Date) -LocalizedName "$ApplicationName $ApplicationSWVersion" -LocalizedDescription "$ApplicationDescription" -UserDocumentation $ApplicationDocURL -IconLocationFile $ApplicationIcon`

Same applies for line 376

**Comment by asjimene** [comment]
Fixed this long ago. Not sure why I didn't close :)
