### ISSUE TITLE
Add "Or" Detection Method Connector

### ISSUE THREAD

**Issue by DammittJim** [asjimene/SCCM-Application-Packager#3]
Hello,

Apologies if this isn't the correct place for this. This is my first post here.

I may have missed it somewhere in either the Powershell script or the Template.xml, but I can't see a way of setting the detection method connector to "And" or "Or" when setting up more than one detection clause. Is there a way to do this and if so are you able to add it into either the template.xml or the powershell script?

Many Thanks,
Jim

**Comment by asjimene** [comment]
This is the right place to post, I don't really have a blog or anything, For now, only "And" is supported when adding multiple detection method clauses, and it is automatically done just by having 2 clauses under the "CustomDetectionMethods".

Here is an example of an "And" detection method section for Firefox:
```
			<CustomDetectionMethods>
				<DetectionClause>
					<DetectionClauseType>File</DetectionClauseType>
					<Name>firefox.exe</Name>
					<Path>%ProgramFiles%\Mozilla Firefox</Path>
					<PropertyType>Version</PropertyType>
					<ExpectedValue>$FullVersion</ExpectedValue>
					<ExpressionOperator>IsEquals</ExpressionOperator>
					<Value>True</Value>
				</DetectionClause>
				<DetectionClause>
					<DetectionClauseType>File</DetectionClauseType>
					<Name>helper.exe</Name>
					<Path>%ProgramFiles%\Mozilla Firefox\uninstall</Path>
					<PropertyType>Version</PropertyType>
					<ExpectedValue>$FullVersion</ExpectedValue>
					<ExpressionOperator>IsEquals</ExpressionOperator>
					<Value>True</Value>
				</DetectionClause>
			</CustomDetectionMethods>
```

I have added notes for multiple detection clauses to the template. I will change this issue to an "enhancement". In the meantime, you can always set a powershell script as your detection method. :)

**Comment by DammittJim** [comment]
Thanks for your response. Yes, the example you gave for the "And" connector was what I ended up using. Hopefully the detection method connector for "Or" will be supported soon as this would be very useful for some of the other applications we use.

Also, thank you and the other contributors for the script. It really is fantastically useful!

**Comment by asjimene** [comment]
Connectors have been added for SCCM Sites version 1810 or higher with version 2.1 released today.
