### ISSUE TITLE
Wrong WMI class for "AutoPackage - OSArchitecture x64" condition

### ISSUE THREAD

**Issue by cedricmordrin** [asjimene/SCCM-Application-Packager#4]
AutoPackage - OSArchitecture x64 condition creates a rule for the Win32_ComputerSystem class looking for an OSArchitecture property. This property is a member of the Win32_OperatingSystem class.

Line 33 of CreateGlobalConditionsAndRequirements.ps1 should be the following:
`New-CMGlobalConditionWqlQuery -DataType String -Class Win32_OperatingSystem -Namespace root\cimv2 -Property OSArchitecture -WhereClause "OSArchitecture = `'64-bit`'" -Name "AutoPackage - OSArchitecture x64" -Description "Returns True if Win32_OperatingSystem is True. Use as existential rule for 64-bit operating system"`

**Comment by asjimene** [comment]
Copy-paste strikes again! This is fixed in the latest commit. Thanks!

**Comment by asjimene** [comment]
Reopening this issue. The Global Condition is now correct, but the requirement added to the template app (and the requirements in the recipes) are incorrect. They should be existential not True/False
