### ISSUE TITLE
Script didn't work until I added New-PSDrive declaration

### ISSUE THREAD

**Issue by jholl016** [asjimene/SCCM-Application-Packager#5]
FYI, I was getting errors any time the Set-Location cmdlet tried to change to the CMSite provider location because a PSDrive for that provider had never been established.  I added the missing New-PSDrive logic at the appropriate location in the main script and everything is good now.

**Comment by asjimene** [comment]
Hmm, I've never run into that issue, but I think i have heard of it. Did you ever open the Console with the user that was running the script?

Regardless, is the command you ran something like this:
new-psdrive -Name $SiteCode -PSProvider "AdminUI.PS.Provider\CMSite" -Root "$ENV:ComputerName" -Description "SCCM Site" 

Please let me know and I will add it to the script. Thanks for bringing this up :)

**Comment by jholl016** [comment]
You know, I don't think ever did.  I probably just installed the console to get the PS modules and then went straight to testing your scripts.

I'm not running the script on my site server, so my code is slightly different from yours, but yes that's the basic idea.

![image](https://user-images.githubusercontent.com/30354773/58645047-8f454200-82d0-11e9-8f5b-becd491a5771.png)

**Comment by asjimene** [comment]
Awesome! That is exactly what I needed. Thank you!

**Comment by jholl016** [comment]
This is a super impressive solution.  I had done some similar automation for just one or two apps in my org a while ago, but the way you've generalized this and started a community repo for these "recipes" is fantastic.  Do you have a blog about this solution I can point people to, or is this GitHub page the best thing to share?

**Comment by asjimene** [comment]
Thank you, that means a lot! I took inspiration from the autopkg project for Mac https://github.com/autopkg/autopkg and kinda ran with it. I have not blogged about it yet (I plan to do that when I get some time someday), however, I did present on it at the latest AZ Systems Management User Group meeting here: https://miketerrill.net/2019/05/14/azsmug-presents-intune-rbac-graph-autopilot-and-more/ besides that, the github is the best place to point people for sure, and I have a link to my presentation slides here: https://github.com/asjimene/miscellaneous-tools/tree/master/AZSMUG-5-2019

If you have any suggestions, feel free to let me know!

**Comment by jholl016** [comment]
Not sure if you're aware, but PatchMyPC (which is a great product, and we use it at my company) is working on doing something very similar to this, but they're charging extra for it.  Not to mention their first draft effort is creating packages, not applications.  You've already nailed it and you're sharing it freely, lol.  Thanks for sharing!

**Comment by asjimene** [comment]
I did not know about that! I have heard about PatchMyPC and they seem like a great product, would probably simplify my job quite a bit lol. That is very interesting indeed! You are welcome, I have gotten so much knowledge an tools from the community, I figured I could give back as well!

**Comment by cedricmordrin** [comment]
They hope to have the applications based deployments out by MMS Jazz Edition. I currently use them for patching, but have this run every morning for my apps.

I've created some extra recipes I need to submit up-channel.


--

Andrew


________________________________
